# Generated by Django 3.2.7 on 2021-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
    ]
