# Generated by Django 3.2.7 on 2021-10-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_update_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_update_view',
            old_name='product',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order_update_view',
            name='customer',
        ),
    ]
