# Generated by Django 3.2.7 on 2021-10-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20211004_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update_view',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
