# Generated by Django 3.2.7 on 2021-10-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.transporter'),
        ),
    ]
